apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hostinfo
  name: hostinfo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hostinfo
status:
  loadBalancer: {}
